- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/zh_CN.json
> Update translation strings as of 20190718T220243

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/zh_CN.json
> Update translation strings as of 20190820T134838

- translations/ui-finc-select/it_IT.json
> Update translation strings as of 20190918T144452

- translations/ui-finc-select/it_IT.json
> Update translation strings as of 20190919T124724

- translations/ui-finc-select/it_IT.json
> Update translation strings as of 20190925T125755

- translations/ui-finc-select/ar.json
> Update translation strings as of 20191004T135530

- translations/ui-finc-select/es_ES.json
> Update translation strings as of 20191216T170438

- translations/ui-finc-select/fr_FR.json
> Update translation strings as of 20200117T173544

- translations/ui-finc-select/fr.json
> Update translation strings as of 20200127T144839

- translations/ui-finc-select/fr_FR.json
> Update translation strings as of 20200217T172736

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200220T141728

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200302T163727

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200309T000645

- translations/ui-finc-select/pt_BR.json
> Update translation strings as of 20200312T133304

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200316T134017

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/pt_BR.json
> Update translation strings as of 20200317T123814

- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/ru.json
> Update translation strings as of 20200319T202257

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200423T142657

- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200513T135229

- translations/ui-finc-select/ru.json
> Update translation strings as of 20200626T180122

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200701T150841

- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
> Update translation strings as of 20200709T123052

- translations/ui-finc-select/pt_BR.json
> Update translation strings as of 20200710T132222

- translations/ui-finc-select/fr_FR.json
> Update translation strings as of 20200716T140311

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200721T202356

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200723T031126

- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/ru.json
> Update translation strings as of 20200723T131158

- src/components/Filters/FilterFilters.js
- src/components/Filters/Filters.js
- src/components/MetadataCollections/CollectionFilters.js
- src/components/MetadataCollections/MetadataCollections.js
- src/components/MetadataSources/MetadataSources.js
- src/components/MetadataSources/SourceFilters.js
- translations/ui-finc-select/en.json
The translation-errors are gone, but now yarn test can't complete. Maybe it is because this PR has not merged jet?
https://github.com/folio-org/ui-finc-select/pull/132
> Uifc 198 fix react intl error

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200804T124827

- translations/ui-finc-select/ar.json
- translations/ui-finc-select/ca.json
- translations/ui-finc-select/da.json
- translations/ui-finc-select/de.json
- translations/ui-finc-select/en_GB.json
- translations/ui-finc-select/en_SE.json
- translations/ui-finc-select/en_US.json
- translations/ui-finc-select/es.json
- translations/ui-finc-select/es_419.json
- translations/ui-finc-select/es_ES.json
- translations/ui-finc-select/fr.json
- translations/ui-finc-select/fr_FR.json
- translations/ui-finc-select/he.json
- translations/ui-finc-select/hi_IN.json
- translations/ui-finc-select/hu.json
- translations/ui-finc-select/it_IT.json
- translations/ui-finc-select/ja.json
- translations/ui-finc-select/ko.json
- translations/ui-finc-select/pl.json
- translations/ui-finc-select/pt_BR.json
- translations/ui-finc-select/pt_PT.json
- translations/ui-finc-select/ru.json
- translations/ui-finc-select/ur.json
- translations/ui-finc-select/zh_CN.json
- translations/ui-finc-select/zh_TW.json
> Update translation strings as of 20200928T202231

- translations/ui-finc-select/ar.json
> Update translation strings as of 20200930T202600

- translations/ui-finc-select/fr_FR.json
> Update translation strings as of 20201020T221939

- translations/ui-finc-select/it_IT.json
> Update translation strings as of 20201110T192302

- translations/ui-finc-select/it_IT.json
> Update translation strings as of 20201111T142927

- translations/ui-finc-select/fr_FR.json
> Update translation strings as of 20201119T214636

- package.json
- src/components/Filters/FilterFile/FilterFileForm.js
- src/components/Filters/FilterFile/FilterFileView.js
- src/components/Filters/FilterFile/FilterFileView.test.js
- src/components/Filters/FilterFile/UploadFile/DocumentsFieldArray.js
- src/components/Filters/FilterFile/UploadFile/FileUploaderField.js
- src/components/Filters/FilterFile/UploadFile/FileUploaderFieldView.js
https://issues.folio.org/browse/UIFC-277
> UIFC-277: fix yarn test download

- package.json
- src/routes/SourcesRoute.js
https://issues.folio.org/browse/UIFC-300
> UIFC-300: no results shown on first open

- jest.config.js
- package.json
- src/components/Filters/FilterFile/UploadFile/DocumentsFieldArray.js
https://issues.folio.org/browse/UIFC-299
> UIFC-299: upgrade stripes-erm-components

- CHANGELOG.md
- src/components/DisplayUtils/fetchWithDefaultOptions.js
- src/components/DisplayUtils/fetchWithDefaultOptions.test.js
- src/components/Filters/FilterFile/FilterFileForm.js
- src/components/Filters/FilterFile/FilterFileView.js
- src/components/MetadataCollections/CollectionInfo/SelectUnselect.js
- src/components/MetadataSources/SourceManagement/SelectAllCollections.js
- src/routes/utilities/saveCollectionIds.js
https://issues.folio.org/browse/UIFC-316
> UIFC-316: leverage cookie based authentication in all api requests

- package.json
* Remove visible `finc-select.enabled` permission
* Remove unrequired permissions from `settings.manage`
* Expand `finc-select.all`
* Add missing `finc-config.metadata-sources.collection.get` perm
> UIFC-321 Update permissions

- CHANGELOG.md
- src/components/Filters/FilterForm.js
- src/components/Filters/FilterView.js
- src/components/Filters/Filters.js
- src/components/MetadataCollections/MetadataCollectionView.js
- src/components/MetadataCollections/MetadataCollections.js
- src/components/MetadataSources/MetadataSourceView.js
- src/components/MetadataSources/MetadataSources.js
- src/settings/CredentialsSettingsForm.js
https://issues.folio.org/browse/UIFC-339
> UIFC-339-remove-deprecated-properties

- CHANGELOG.md
- src/components/MetadataCollections/CollectionInfo/SelectUnselect.js
- src/components/MetadataCollections/MetadataCollectionView.test.js
- src/components/MetadataSources/MetadataSourceView.test.js
- src/components/MetadataSources/SourceManagement/SelectAllCollections.js
https://issues.folio.org/browse/UIFC-322
> UI fc 322 buttons should be disabled if no permissions

- CHANGELOG.md
- src/components/Filters/FilterForm.js
- translations/ui-finc-select/en.json
https://folio-org.atlassian.net/browse/UIFC-348
> UIFC-348: SaveAndClose translation key

- CHANGELOG.md
- src/routes/FiltersRoute.js
https://folio-org.atlassian.net/browse/UIFC-377
> UIFC-377: Fix handleNeedMoreData

- CHANGELOG.md
- package.json
- src/components/Filters/FilterForm.test.js
- test/jest/__mock__/currencyData.mock.js
- test/jest/__mock__/index.js
- test/jest/__mock__/matchMedia.mock.js
- test/jest/__mock__/reactIntl.mock.js
- test/jest/__mock__/stripesConfig.mock.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/__mock__/stripesIcon.mock.js
- test/jest/__mock__/stripesSmartComponents.mock.js
https://folio-org.atlassian.net/browse/UIFC-379
> UIFC-379: Fix tests

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIFC-387
See https://github.com/folio-org/mod-finc-config/pull/152
> [UIFC-387] Update required interfaces

- CHANGELOG.md
- src/components/DisplayUtils/urls.js
- src/components/Filters/Filters.js
- src/components/MetadataCollections/MetadataCollections.js
- src/components/MetadataSources/MetadataSources.js
- src/components/Navigation/Navigation.js
- src/routes/CollectionsRoute.js
https://folio-org.atlassian.net/browse/UIFC-370
> UIFC-370: Refactor localstorage

- CHANGELOG.md
- src/components/DisplayUtils/EditCard/EditCard.test.js
- src/components/Filters/FilterFile/FilterFileForm.test.js
- src/components/Filters/FilterFile/FilterFileView.test.js
- src/components/Filters/FilterFile/UploadFile/DocumentsFieldArray.test.js
- src/components/Filters/FilterForm.test.js
- src/components/Filters/FilterView.test.js
- src/components/Filters/Filters.js
- src/components/Filters/Filters.test.js
- src/components/MetadataCollections/MetadataCollectionView.test.js
- src/components/MetadataCollections/MetadataCollections.js
- src/components/MetadataCollections/MetadataCollections.test.js
- src/components/MetadataSources/MetadataSourceView.test.js
- src/components/MetadataSources/MetadataSources.js
- src/components/MetadataSources/MetadataSources.test.js
- src/index.test.js
- src/routes/CollectionsRoute.test.js
- src/routes/SourcesRoute.test.js
- test/fixtures/metadatasources.js
- test/jest/helpers/renderWithIntlConfiguration.js
- test/jest/helpers/withIntlConfiguration.js
https://folio-org.atlassian.net/browse/UIFC-399
> UIFC-399: Refactor tests

- CHANGELOG.md
- src/components/DisplayUtils/ViewContainer.js
- src/components/DisplayUtils/renderListUtils.js
- src/components/Filters/FilterFile/FilterFileView.js
- src/components/Filters/FilterFilters.js
- src/components/Filters/FilterView.js
- src/components/Filters/Filters.js
- src/components/MetadataCollections/CollectionFilters.js
- src/components/MetadataCollections/MetadataCollectionView.js
- src/components/MetadataCollections/MetadataCollections.js
- src/components/MetadataSources/MetadataSourceView.js
- src/components/MetadataSources/MetadataSources.js
- src/components/MetadataSources/SourceFilters.js
- src/components/hooks/useUpdatedFilters.js
- src/routes/CollectionsRoute.js
https://folio-org.atlassian.net/browse/UIFC-342
> UIFC-342: Address code duplications

- CHANGELOG.md
- src/components/DisplayUtils/NoPermissionsMessage.js
- src/routes/CollectionsRoute.js
- src/routes/CollectionsRoute.test.js
- src/routes/FiltersRoute.js
- src/routes/FiltersRoute.test.js
- src/routes/SourcesRoute.js
- src/routes/SourcesRoute.test.js
https://folio-org.atlassian.net/browse/UIFC-434
> UIFC-434: Add permission check

- CHANGELOG.md
- src/settings/CredentialsSettings.js
https://folio-org.atlassian.net/browse/UIFC-444
> UIFC-444: Fix settings ezb credentials
